name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  core:
    strategy: 
      matrix:
        os: [ubuntu, macos, windows]
        toolchain: [stable, nightly]

    runs-on: ${{ matrix.os }}-latest

    defaults:
      run:
        working-directory: ./core

    steps:
    - uses: actions/checkout@v4

    - name: Install toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        targets: "x86_64-unknown-uefi, aarch64-unknown-uefi, i686-unknown-uefi"
        components: "rust-src, rustfmt, clippy"

    - name: Build
      run: cargo build
      
    - name: Lint
      run: cargo clippy
      
    - name: Check formatting
      run: cargo fmt --check
      
  make_img:
    strategy: 
      matrix:
        os: [ubuntu, macos, windows]
        toolchain: [stable, nightly]

    runs-on: ${{ matrix.os }}-latest

    defaults:
      run:
        working-directory: ./make_img

    steps:
    - uses: actions/checkout@v4

    - name: Install toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        components: "rustfmt, clippy"

    - name: Build
      run: cargo build
      
    - name: Lint
      run: cargo clippy
      
    - name: Check formatting
      run: cargo fmt --check
      
    - name: Run tests
      run: cargo test
